language: csharp
solution: Smtpapi/SendGrid.SmtpApi.sln
install:
- nuget restore Smtpapi/SendGrid.SmtpApi.sln
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
- xbuild /p:Configuration=Release Smtpapi/SendGrid.SmtpApi.sln
- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Smtpapi/HeaderTests/bin/Release/SendGrid.SmtpApi.HeaderTests.dll
deploy:
  skip_cleanup: true
  provider: script
  script: nuget push ./Smtpapi/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
  on:
    branch: master
    tags: true
