language: csharp
dotnet: 3.1
env:
- FrameworkPathOverride=/usr/lib/mono/4.5/
install:
- make install
script:
- make test
- make release
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push /home/travis/build/sendgrid/smtpapi-csharp/*.nupkg --api-key
    $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
  on:
    branch: main
    tags: true
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: P30BHIrJdZ4ywIUAzGHqECZJh9oytniQz0SOfCWmHy7V2GQAy5A3UqDL1VbuETy/7XS+JP0G8HzbfIE4tMxU9+MgoF6gRz2n8ls6gbDopHGEJeuI5Ad9AKos2Cb7rnRx5/sWld+EGd3U3c/yQyfx6KLWoXDkxXQExVZVNmdNIio=
